### ISSUE TITLE
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by Quraian** [ngxs/schematics#157] opened 2021-12-05 10:20 UTC
I tried this on a new clean Angular 13 app, but I get an error after I try **ng add @ngxs/schematics:**

<pre>
Skipping installation: Package already installed
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID

[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (D:\Code\ngtemp\node_modules\ajv\dist\vocabularies\core\id.js:6:15)
    at keywordCode (D:\Code\ngtemp\node_modules\ajv\dist\compile\validate\index.js:454:13)
    at D:\Code\ngtemp\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (D:\Code\ngtemp\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (D:\Code\ngtemp\node_modules\ajv\dist\compile\codegen\index.js:568:18)
    at iterateKeywords (D:\Code\ngtemp\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (D:\Code\ngtemp\node_modules\ajv\dist\compile\validate\index.js:208:13)
    at D:\Code\ngtemp\node_modules\ajv\dist\compile\validate\index.js:192:13
    at CodeGen.code (D:\Code\ngtemp\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (D:\Code\ngtemp\node_modules\ajv\dist\compile\codegen\index.js:568:18)
</pre>

**Comment by OleksandrYatsiuk** [comment] 2022-01-22 08:27
I added a pull request early https://github.com/ngxs/schematics/pull/153.

**Solution for now (local using):**
in ```node_modules/@ngxs/schematics/src/factories/*``` change schematic ```"id"``` to ```"$id"``` for needed commands.

**Comment by jaytonic** [comment] 2022-04-27 09:07
Same issue for me. Workaround works, would be great to have this released

**Comment by akialapiha** [comment] 2022-07-28 05:29
Still facing the same issue (using NX with angular version 14,  tried to run `npm install @ngxs/schematics && npx nx g @ngxs/schematics:ng-add`) - Yes the workaround works but having minor stuff like this hanging open makes me wonder if NGXS is safe to use from the perspective of maintenance.

**Comment by jaytonic** [comment] 2022-08-12 06:49
Still have the issue, I removed the 

 ```
 "cli": {
    "schematicCollections": [
      "@ngxs/schematics"
    ]
  }
```

in my angular.json file since I was not using much the cli to create my store.

**Comment by datpt154** [comment] 2022-10-03 04:17
The problem is still remaining on 0.0.1-alpha.5 eventhough the fix is merged on master branch for a long time ago?

**Comment by joshdbwh** [comment] 2022-10-07 03:31
> The problem is still remaining on 0.0.1-alpha.5 eventhough the fix is merged on master branch for a long time ago?

Bumping this. Can anyone address this issue? This ticket was made almost a year ago. @OleksandrYatsiuk

**Comment by OleksandrYatsiuk** [comment] 2022-10-08 12:53
> > The problem is still remaining on 0.0.1-alpha.5 eventhough the fix is merged on master branch for a long time ago?
> 
> Bumping this. Can anyone address this issue? This ticket was made almost a year ago. @OleksandrYatsiuk

I think that we need a new version of the library.

**Comment by RobertDiebels** [comment] 2023-03-11 09:34
Bumping this too. Do the schematics not have a proper release schedule?

**Comment by FelipeSanchezCalzada** [comment] 2023-07-17 22:09
Hi @markwhitfeld! Can you take a look at this? We only need a new release.

For now, i fix it with:
`npm install https://github.com/ngxs/schematics.git -D
`

**Comment by cozmik** [comment] 2023-08-25 07:48
Still no fix for this??

**Comment by sunandakiranagi** [comment] 2024-09-26 06:24
Any updates on this

**Comment by markwhitfeld** [comment] 2024-09-26 14:17
Hi everyone, apologies, we had been missing these notifications because the NGxS schematics are no monger maintained in this repository.
They are now part of the `@ngxs/store` package.
See docs here: https://www.ngxs.io/introduction/schematics
As a side note, we are looking for feedback on, and improvement to, the default schematics. Please go ahead and submit any contributions in the main `ngxs/store` github repository.

**Closed by markwhitfeld** 2024-09-26 14:17 UTC
